{% set name = "Flask-Migrate" %}
{% set version = "2.6.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8626af845e6071ef80c70b0dc16d373f761c981f0ad61bb143a529cab649e725

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - flask >=0.9
    - flask-sqlalchemy >=1.0
    - alembic >=0.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flask_migrate

about:
  home: https://github.com/miguelgrinberg/flask-migrate/
  license_file: LICENSE
  license: MIT
  summary: 'SQLAlchemy database migrations for Flask applications using Alembic'
  dev_url: https://github.com/miguelgrinberg/flask-migrate/
  doc_url: https://flask-migrate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
