{%set name = "Flask-Migrate" %}
{%set version = "2.0.4" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "1e6dc83bed93aef9a4791d5daaa03b186c8ef5d96c99c7d88166da683c86e42d" %}
{%set build_num = "0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  preserve_egg_dir: True
  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - flask >=0.9
    - flask-sqlalchemy >=1.0
    - alembic >=0.6
    - flask-script >=0.6

test:
  imports:
    - flask_migrate

about:
  home: http://github.com/miguelgrinberg/flask-migrate/
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'SQLAlchemy database migrations for Flask applications using Alembic'
  dev_url: https://flask-migrate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - pmlandwehr
