{% set name = "Flask-Migrate" %}
{% set version = "2.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e2217ff18b98df27adbf6cc51eaa5f074c9e22f06074b47ebc7b29d2f545eccc

build:
  noarch: python
  number: 0
  script: pip install -vv .

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - flask >=0.9
    - flask-sqlalchemy >=1.0
    - alembic >=0.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flask_migrate

about:
  home: https://github.com/miguelgrinberg/flask-migrate/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'SQLAlchemy database migrations for Flask applications using Alembic'
  dev_url: https://github.com/miguelgrinberg/flask-migrate/
  doc_url: https://flask-migrate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
