{% set name = "Flask-Migrate" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 7dd4884825f19ffb2a6e6903c097674b0f6b7e826ec04f52a07fec477a711631

build:
  noarch: python
  number: 0
  script: pip install -vv .

requirements:
  build:
    - python >=2.7
    - pip
  run:
    - python >=2.7
    - flask >=0.9
    - flask-sqlalchemy >=1.0
    - alembic >=0.7

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flask_migrate

about:
  home: https://github.com/miguelgrinberg/flask-migrate/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'SQLAlchemy database migrations for Flask applications using Alembic'
  dev_url: https://github.com/miguelgrinberg/flask-migrate/
  doc_url: https://flask-migrate.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - jan-janssen
    - xhochy
