# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "vCpidFkebvK61ppvEuguO9gv/5tONGTMsNWtoQ8ekIccUm+D8G/7XZ7pBaj4ov6S9Qr0/Bt1z7nhJ2gDIY0hB5/tJOO6oqlLMmwW237KQ+1tryMbWtKgOyqmAZVU/MC60lxOtGIAufUafYaDNIN7yMDr/192014X26AKRuBMeTlB4H6sROlFpgl6Exv7EnY0U50IYe81F6Bka02Wt0lKn0QW6rJgN+IdBhG7tkO7F19DhSVC0DD8D92x2NPtMAa6Pp59HCAHZ/1UUb16H968qNu2GMa+Vl4XfiO+x4BeOtfzLzdK03YbOqgL5tdUNLhbwS6wyMImkp5PBcv2mPIpwvGiLV+bHh1CGblc8c0ExdEK/lLQoJASSuBakxJNMd+eVSGJgK1SJYRvGqglvuVksec2/JHUXBEaA/NLeDOjEParFsTlDn0EzZK21VO20e6/as/d+0hc4XBuUKTxmeIHttmZ3+uodqhjKjuBvTG4KrLcTMYyOJG2UP/wJKQN9092Xq+siO8DNMqn7v+Usf7tKSRFJzyJfkzJwF4TBHYvGIuU8iilpjFHja38if+Y4cOgvb1VyeU/JU7GBeG0aKNz9SxhA1OX9Tzf1kGsbbfiBrWk1EEBFm80QsJmsOJRpm/R0Fu1J4pkrgSnEW/exlZhmmNR+nvaDQWTcuzieb4fQFA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
