travis:
  secure:
    BINSTAR_TOKEN: T2D82yQ5QHvWlUVzFfAroJqWXXF505TmeqHpI8jSMcn1HZXDBEHhE3ZyylrHH9YyUhiQmRjUZuT5XmbvZlc2XkRWZEWQdyDJQaH/6CdFjJEMCZcaVHmRCjSbyiqr30OmGQJfrr5MVLGBDhdzUeisyOpI74capaBgEkOoK4US3gLTBU8ZpeAWyROaGum+Ai2Wld5VNqr4iev6U6Ab6CNJMw5xoCUp88gSCOC22BmDI6Hpz8RubW3SsKLSckmiPkZoH78IpaWarrPGbswUsssbAg0Ubukoiw/LjUgby0xuPeBTtY6VBY2HYOaLYsq5X1/rc9JDC2byFjT5nBvuDUT9CqaWvpWQQPAo9fbqmf2YXRv3XJ2BKdwKXhk+nKXkVxmYclyggz1effbgDp3IKh2eItiEvsHZVU3ovwu9fXeDy7a++cgxRF8U7FrdZdiKgWSX76pumLuUe3kbdqGrQ3Lfg3vA96p/hl30Xm62WtKehy71Zgt4RBDWGioSQVHox0+RFQmR7ylUUWHHCZ05laMOvvMgioy+CDsqQQDP7oLbQWWF+P9aAklqBVAM9Hcw5j+ZoUQ94hNRanT4eSaa25Hp8xP2xUxX7v6fQ2ITe3gdv92E1z0RUYdXsIobOXp6w9o5NtwJnID3xaOoN8pUXPKAnLBvz72RuqiPr3IYLPWWBOM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
